language: php

php:
  - 7.0

env:
  - REPORT_EXIT_STATUS=1

before_install:
  - sudo apt-get install freeglut3-dev;
  - sudo apt-get install -qq --force-yes mesa-utils libgl1-mesa-swx11 libgl1-mesa-swx11-dev xvfb  

before_script:
  - phpize
  - ./configure --quiet
  - make all install
  - echo "extension=opengl.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - export LIBGL_ALWAYS_SOFTWARE=1
  - export DISPLAY=:99
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render
  - glxinfo

script:
  - DISPLAY=:99 TEST_PHP_EXECUTABLE=$(which php) make test

