name: Build and test

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - name: Build and tag SDL image
          run: docker build -f php-sdl.Dockerfile -t ponup/php-sdl .
        - name: Build and tag image
          run: docker build -t ponup/php-opengl .
        - name: Run tests
          run: docker run --rm ponup/php-opengl
